# Introduction to Data Analysis with Pandas

Pandas is an open-source Python library built on top of NumPy, first released by Wes McKinney in 2008.
It is a high-level library known for its efficiency in handling structured data. Pandas supports multiple data workflows, including data cleaning, transformation, and analysis, which is why it is essential for data science and artificial intelligence.
It has a large ecosystem of integrations, making it suitable for a wide range of applications, from financial modeling and business analytics to preprocessing features for machine learning models.

---

Originally, there are 2 core data structures in Pandas:

- Series (1-Dimensional):

The data is structured as a single column of values, capable of holding any data type (integers, strings, floats, etc.).

Every element is explicitly mapped to an axis label, known as the index.

Mathematical operations are vectorized, allowing you to perform calculations across the entire series instantly without writing loops.

- DataFrame (2-Dimensional):

The entire data collection is structured as a tabular spreadsheet with distinct rows and columns.

It is exceptionally faster than native Python collections because the underlying data is stored in contiguous memory blocks.

However, managing memory can become a challenge with massive datasets, as a simple operation can create unintended copies of the entire structure in memory.

In [1]:
# Importing libraries
import pandas as pd
import numpy as np
from numpy import nan as Na

<h3> Working with Series

In [ ]:
# Creating a series
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s.index) # an attr returning index of series

data = pd.Series([[1,2,3],[4,5,6],2,5,{"name": "Huzaifa", "age":27}])
data

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

0                         [1, 2, 3]
1                         [4, 5, 6]
2                                 2
3                                 5
4    {'name': 'Huzaifa', 'age': 27}
dtype: object

Think of a Series as a column in Excel. When you do: s*2, Pandas automatically multiplies every cell in that column by 2.  
This behavior is called **vectorized operations**.

In [11]:
# Performing mathematical operations using series
s = s**3 # cube of every item
s

a      1
b      8
c     27
d     64
e    125
dtype: int64

In [12]:
# Selecting or modifying an element
s['a'] = 0
s

a      0
b      8
c     27
d     64
e    125
dtype: int64

In [13]:
print(f"Sum: {s.sum()}") # aggregate func which calculates sum of all items
print(f"Avg: {s.mean()}")

Sum: 224
Avg: 44.8

In [16]:
# Operations between 2 series
s1 = pd.Series([1,2,3])
s2 = pd.Series([10,20,30, 0])
s3 = s1 + s2 # adds s1 element to its corresponding s2 element (s1[0]+s2[0] = s3[0])
s3

0    11.0
1    22.0
2    33.0
3     NaN
dtype: float64

<h3> Dealing with DataFrames

In [ ]:
# Creating a DataFrame
df_1 = pd.DataFrame({
    "name": ["Ali", "Sarah", "George"], # --> column-wise insertion
    "marks": [76,93,56]
})
print(df_1)

std_data = [["Ali", 1000], ["Sarah", 1001], ["George", 1002]] # --> row-wise insertion
df_2 = pd.DataFrame(std_data, columns=["name", "ID"])
print(f"\n{df_2}")

     name  marks
0     Ali     76
1   Sarah     93
2  George     56

     name    ID
0     Ali  1000
1   Sarah  1001
2  George  1002

In [17]:
# Merging Datasets
merged_df = pd.merge(df_1, df_2)
merged_df

     name  marks    ID
0     Ali     76  1000
1   Sarah     93  1001
2  George     56  1002

In [14]:
# Concatenating 2 datasets
df_3 =  pd.DataFrame({
    "name": ["Daniel", "Mustufa"],
    "marks": [34,98],
})

final_df = pd.concat([df_1, df_3])
final_df

      name  marks
0      Ali     76
1    Sarah     93
2   George     56
0   Daniel     34
1  Mustufa     98

In [ ]:
# Creating new columns named "grade" and "status" using map function and replace
def grade(m):
    if m >=90:
        return "A"
    elif m >=80:
        return "B"
    elif m>=70:
        return "C"
    elif m>=60:
        return "D"
    else:
        return "U (Ungraded)"
    
final_df["grade"] = list(map(grade, final_df["marks"]))
final_df["Status"] = list(map(lambda x: x>=60, final_df["marks"]))
final_df["Status"] = final_df["Status"].replace({True: "Promoted", False : "Failed"})
final_df

      name  marks         grade    Status
0      Ali     76             C  Promoted
1    Sarah     93             A  Promoted
2   George     56  U (Ungraded)    Failed
0   Daniel     34  U (Ungraded)    Failed
1  Mustufa     98             A  Promoted

In [ ]:
# Using map for calculating new columns
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
 'Pastrami', 'corned beef', 'Bacon',
 'pastrami', 'honey ham', 'nova lox'],
 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
 
data["food"] = data["food"].str.lower()

meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

data["meat_to_animal"] = data["food"].map(lambda x: meat_to_animal[x]) 
data

          food  ounces meat_to_animal
0        bacon     4.0            pig
1  pulled pork     3.0            pig
2        bacon    12.0            pig
3     pastrami     6.0            cow
4  corned beef     7.5            cow
5        bacon     8.0            pig
6     pastrami     3.0            cow
7    honey ham     5.0            pig
8     nova lox     6.0         salmon