# Introduction to Pandas, Series, and DataFrames

## Definition

**Pandas** is an open-source Python library designed for data manipulation, cleaning, transformation, and analysis. It provides high-performance, easy-to-use data structures built directly on top of **NumPy**, allowing developers to work efficiently with tabular, labeled, and relational datasets.

The core functionality of Pandas rests on two primary data structures:

* **Series**: A one-dimensional labeled array capable of holding any data type (integers, floats, strings, Python objects).
* **DataFrame**: A two-dimensional, size-mutable, tabular data structure with labeled axes (rows and columns), similar to a spreadsheet, SQL table, or dictionary of Series objects.

---

## Why It Matters

Raw data in real-world applications is rarely clean, well-structured, or directly usable. While standard Python lists and dictionaries handle basic collections, they lack optimized performance and vector operations for handling thousands or millions of records. Standard NumPy arrays allow fast numerical computation, but they lack column labels, variable-specific data types, and row indices.

Pandas bridges this gap by offering:

* **Labeled Indexing**: Automatic alignment of data across rows and columns using explicit, user-friendly labels.
* **Mixed Data Types**: Support for multiple data types across different columns within a single unified structure.
* **Integrated Alignment**: Automatic handling of missing data and structural alignment during arithmetic operations.
* **Data I/O Capability**: Built-in functionality to import and export data across formats such as CSV, Excel, SQL databases, and JSON.

---

## The Core Data Structures

Understanding how Pandas organizes data requires recognizing the structural difference between a **Series** and a **DataFrame**.

### 1. Pandas Series

A **Series** represents a single column of data. It consists of two main visual and functional components:

* **Index**: An array of explicit labels pointing to each element (defaults to integer positions `0, 1, 2...` if not explicitly declared).
* **Values**: The underlying data array storing the actual elements.

> Conceptually, a Series can be thought of as a fixed-size, ordered dictionary mapping explicit index keys to data values.

### 2. Pandas DataFrame

A **DataFrame** represents an entire table containing multiple variables. It consists of three main structural components:

* **Row Index**: Labels identifying each individual row observation.
* **Column Index**: Labels identifying each variable column.
* **Values Matrix**: A two-dimensional array storing the table's underlying values.

> Conceptually, a DataFrame acts as a collection of individual **Series** objects that share the exact same row index.

---

## Key Differences

| Feature | Pandas Series | Pandas DataFrame |
| --- | --- | --- |
| **Dimensions** | 1-Dimensional | 2-Dimensional |
| **Structure** | Single column with an index | Multiple columns sharing a common row index |
| **Data Types** | Holds a single data type across all elements | Can hold different data types across different columns |
| **Representation** | Represents a single variable or feature | Represents a complete tabular dataset or observational table |

---

## Basic Indexing and Data Selection

Pandas provides two explicit indexing mechanisms for selecting subsets of data:

* **Label-Based Indexing (`.loc[]`)**: Selects data based on explicitly named row and column labels.
* **Positional Indexing (`.iloc[]`)**: Selects data using integer-based positional locations (0-indexed).

> Using explicit `.loc[]` and `.iloc[]` accessors avoids subtle reference bugs and unexpected assignment behavior compared to chain-indexing.

---

## Common Mistakes

* **Confusing Series with 1D NumPy Arrays**
* Unlike NumPy arrays, a Pandas Series maintains explicit labeled indices that automatically re-align during mathematical operations.


* **Modifying Data Slices directly Without `.copy()`**
* Slicing a DataFrame often creates a reference view rather than a distinct object. Modifying it can raise a `SettingWithCopyWarning`.


* **Assuming Indices Are Always Sequential Integers**
* Pandas indices can be custom string values, timestamps, non-sequential integers, or duplicate values. Always check the index structure before selecting rows programmatically.



---

## Quick Recap

* **Pandas** provides high-performance tabular data structures designed for data manipulation and analysis.
* A **Series** is a 1-dimensional labeled array representing a single variable.
* A **DataFrame** is a 2-dimensional labeled table composed of sharing-indexed Series objects.
* Use **`.loc[]`** for label-based selection and **`.iloc[]`** for position-based selection.

In [1]:
# Importing libraries
import pandas as pd
import numpy as np

In [ ]:
# Creating a series
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s.index) # an attr returning index of series

data = pd.Series([[1,2,3],[4,5,6],2,5,{"name": "Huzaifa", "age":27}])
data

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

0                         [1, 2, 3]
1                         [4, 5, 6]
2                                 2
3                                 5
4    {'name': 'Huzaifa', 'age': 27}
dtype: object

In [11]:
# Performing mathematical operations using series
s = s**3 # cube of every item
s

a      1
b      8
c     27
d     64
e    125
dtype: int64

In [12]:
# Selecting or modifying an element
s['a'] = 0
s

a      0
b      8
c     27
d     64
e    125
dtype: int64

In [13]:
print(f"Sum: {s.sum()}") # aggregate func which calculates sum of all items
print(f"Avg: {s.mean()}")

Sum: 224
Avg: 44.8

In [16]:
# Operations between 2 series
s1 = pd.Series([1,2,3])
s2 = pd.Series([10,20,30, 0])
s3 = s1 + s2 # adds s1 element to its corresponding s2 element (s1[0]+s2[0] = s3[0])
s3

0    11.0
1    22.0
2    33.0
3     NaN
dtype: float64

In [2]:
# Sorting values
s = pd.Series([20, 80, 50, 40], index=['b', 'c', 'a', 'd'])
print(s.sort_index()) # sort by labels on the left
print(s.sort_values()) # sort by whats inside the cells on the right

a    50
b    20
c    80
d    40
dtype: int64
b    20
d    40
a    50
c    80
dtype: int64

In [ ]:
# Creating a DataFrame
df_1 = pd.DataFrame({
    "name": ["Ali", "Sarah", "George"], # --> column-wise insertion
    "marks": [76,93,56]
})
print(df_1)

std_data = [["Ali", 1000], ["Sarah", 1001], ["George", 1002]] # --> row-wise insertion
df_2 = pd.DataFrame(std_data, columns=["name", "ID"])
print(f"\n{df_2}")

     name  marks
0     Ali     76
1   Sarah     93
2  George     56

     name    ID
0     Ali  1000
1   Sarah  1001
2  George  1002

In [ ]:
# Merging DataFrames
merged_df = pd.merge(df_1, df_2)
merged_df

     name  marks    ID
0     Ali     76  1000
1   Sarah     93  1001
2  George     56  1002

In [ ]:
# Concatenating 2 DataFrames
df_3 =  pd.DataFrame({
    "name": ["Daniel", "Mustufa"],
    "marks": [34,98],
})

final_df = pd.concat([df_1, df_3])
final_df

      name  marks
0      Ali     76
1    Sarah     93
2   George     56
0   Daniel     34
1  Mustufa     98

In [ ]:
# Creating new columns named "grade" and "status" using map and replace function 
def grade(m):
    if m >=90:
        return "A"
    elif m >=80:
        return "B"
    elif m>=70:
        return "C"
    elif m>=60:
        return "D"
    else:
        return "U (Ungraded)"
    
final_df["grade"] = list(map(grade, final_df["marks"]))
final_df["Status"] = list(map(lambda x: x>=60, final_df["marks"]))
final_df["Status"] = final_df["Status"].replace({True: "Promoted", False : "Failed"})
final_df

      name  marks         grade    Status
0      Ali     76             C  Promoted
1    Sarah     93             A  Promoted
2   George     56  U (Ungraded)    Failed
0   Daniel     34  U (Ungraded)    Failed
1  Mustufa     98             A  Promoted

In [ ]:
# Using map for calculating meat_to_animal column
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
 'Pastrami', 'corned beef', 'Bacon',
 'pastrami', 'honey ham', 'nova lox'],
 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
 
data["food"] = data["food"].str.lower()

meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

data["meat_to_animal"] = data["food"].map(lambda x: meat_to_animal[x]) 
data

          food  ounces meat_to_animal
0        bacon     4.0            pig
1  pulled pork     3.0            pig
2        bacon    12.0            pig
3     pastrami     6.0            cow
4  corned beef     7.5            cow
5        bacon     8.0            pig
6     pastrami     3.0            cow
7    honey ham     5.0            pig
8     nova lox     6.0         salmon

In [ ]:
df = pd.DataFrame(
    {
        "Name": ["Ali", "Sara", "Ahmed"],
        "Marks": [78, 95, 43]
    },
    index=["A", "B", "C"]
)
df

    Name  Marks
A    Ali     78
B   Sara     95
C  Ahmed     43

In [17]:
# Using loc to row labels 'B' and 'C' of the column named "Marks"
df.loc[['B', 'C'], "Marks"]

B    95
C    43
Name: Marks, dtype: int64

In [10]:
# Using iloc to select the first 2 rows of the 2nd column
df.iloc[:2, 1]

A    78
B    95
Name: Marks, dtype: int64

In [1]:
print("End of Day 2")

End of Day 2