# Basic Data Cleaning

Data cleaning is one of the most critical steps in data analytics. In Pandas, data cleaning generally falls into five major categories:  
1. handling missing data  
2. dealing with duplicates  
3. correcting data types  
4. filtering/transforming strings  
5. and handling outliers.

<h3> 1. Handling Missing Data

In [2]:
import pandas as pd

In [3]:
# Reading the csv
data = pd.read_csv("Online Sales Data.csv") # creates a DataFrame obj
print(type(data))

<class 'pandas.DataFrame'>

In [4]:
data.isna() # returns either val in row is null or not (True --> null, False --> not null)

# Note: Using .isna() alone isn't super intuitive. Its recommended to chain it with .sum() as df.isna().sum() gives you total null values per column

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...
237,False,False,False,False,False,False,False,False,False
238,False,False,False,False,False,False,False,False,False
239,False,False,False,False,False,False,False,False,False
240,False,False,False,False,False,False,False,False,False
241,False,False,False,False,False,False,False,False,False

In [5]:
# Null values per column
print(data.isna().sum())
# Overall null count
print(f"\nTotal null in dataset: {data.isna().sum().sum()}")

Transaction ID      0
Date                0
Product Category    1
Product Name        0
Units Sold          0
Unit Price          1
Total Revenue       0
Region              0
Payment Method      2
dtype: int64

Total null in dataset: 4

In [ ]:
# Filling the missing values by statistical methods (mean, max, min)
data["Product Category"] = data["Product Category"].fillna("No Value")
data["Unit Price"] = data["Unit Price"].fillna(data["Unit Price"].mean()) # fill by avg val
data["Payment Method"] = data["Payment Method"].fillna("No Value")

data.head(n = 10) # n is a keyword arg, which specifies the number of top rowsto be shown, and is set to 5 by default

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,1/1/2024,Electronics,Iphone 14 Pro,2,999.990000,1999.98,North America,Credit Card
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,234.647054,499.99,Europe,PayPal
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.990000,209.97,Asia,Debit Card
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.990000,63.96,North America,No Value
4,10004,1/4/2024,Books,The Da Vinci Code,4,15.990000,63.96,North America,No Value
5,10005,1/5/2024,No Value,Neutrogena Skincare Set,1,89.990000,89.99,Europe,PayPal
6,10006,1/6/2024,Sports,Wilson Evolution Basketball,5,29.990000,149.95,Asia,Credit Card
7,10007,1/7/2024,Electronics,MacBook Pro 16-inch,1,2499.990000,2499.99,North America,Credit Card
8,10008,1/8/2024,Home Appliances,Blueair Classic 480i,2,599.990000,1199.98,Europe,PayPal
9,10009,1/9/2024,Clothing,Nike Air Force 1,6,89.990000,539.94,Asia,Debit Card

<h3> 2. Dealing with Duplicates

# Basic Data Analysis

In [3]:
data

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,1/1/2024,Electronics,Iphone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,NaN,499.99,Europe,PayPal
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,NaN
4,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,NaN
...,...,...,...,...,...,...,...,...,...
237,10236,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
238,10237,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
239,10238,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
240,10239,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
241,10240,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [4]:
data.head() # a method which returns first 5 rows by default

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,1/1/2024,Electronics,Iphone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,1/2/2024,Home Appliances,Dyson V11 Vacuum,1,NaN,499.99,Europe,PayPal
2,10003,1/3/2024,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,NaN
4,10004,1/4/2024,Books,The Da Vinci Code,4,15.99,63.96,North America,NaN

In [5]:
data.sample() # returns 1 sample row from dataset

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
89,10089,3/29/2024,Beauty Products,Sunday Riley Good Genes,1,105.0,105.0,Europe,PayPal

In [6]:
data.tail() # returns last 5 rows from dataset

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
237,10236,8/23/2024,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
238,10237,8/24/2024,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
239,10238,8/25/2024,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
240,10239,8/26/2024,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
241,10240,8/27/2024,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [7]:
data.columns # an attr which returns column names

Index(['Transaction ID', 'Date', 'Product Category', 'Product Name',
       'Units Sold', 'Unit Price', 'Total Revenue', 'Region',
       'Payment Method'],
      dtype='str')

In [18]:
# Selecting specific columns
data[["Product Category",  "Product Name", "Total Revenue"]]

,Product Category,Product Name,Total Revenue
0,Electronics,Iphone 14 Pro,1999.98
1,Home Appliances,Dyson V11 Vacuum,499.99
2,Clothing,Levi's 501 Jeans,209.97
3,Books,The Da Vinci Code,63.96
4,Books,The Da Vinci Code,63.96
...,...,...,...
237,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,159.99
238,Clothing,Nike Air Force 1 Sneakers,270.00
239,Books,The Handmaid's Tale by Margaret Atwood,32.97
240,Beauty Products,Sunday Riley Luna Sleeping Night Oil,55.00
241,Sports,Yeti Rambler 20 oz Tumbler,59.98

In [8]:
print(f"Total Rows: {data.shape[0]}\nTotal Columns: {data.shape[1]}") # an attr returning total rows and columns in the form of tuple

Total Rows: 242
Total Columns: 9

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    242 non-null    int64
 1   Date              242 non-null    str
 2   Product Category  241 non-null    str
 3   Product Name      242 non-null    str
 4   Units Sold        242 non-null    int64
 5   Unit Price        241 non-null    float64
 6   Total Revenue     242 non-null    float64
 7   Region            242 non-null    str
 8   Payment Method    240 non-null    str
dtypes: float64(2), int64(2), str(5)
memory usage: 17.1 KB

In [ ]:
# Descriptive Analysis
data.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count      242.000000  242.000000   241.000000     242.000000
mean     10120.491736    2.161157   234.647054     334.424835
std         69.933652    1.324388   428.464924     484.105136
min      10001.000000    1.000000     6.500000       6.500000
25%      10060.250000    1.000000    29.500000      63.960000
50%      10120.500000    2.000000    89.990000     179.970000
75%      10180.750000    3.000000   249.990000     398.750000
max      10240.000000   10.000000  3899.990000    3899.990000

In [15]:
# If we want to know how much products fall in a specific category, we use .value_counts() method
data["Product Category"].value_counts()

Product Category
Electronics        41
Books              41
Home Appliances    40
Clothing           40
Sports             40
Beauty Products    39
No Value            1
Name: count, dtype: int64

In [29]:
# Grouping data to analyze the avg, max, and min sales of each region
filtered = data[["Region", "Total Revenue"]]
print(f"Avg Sales of each region:\n{filtered.groupby("Region").mean().reset_index()}")
print(f"Max Sales of each region:\n{filtered.groupby("Region").max().reset_index()}")
print(f"Min Sales of each region:\n{filtered.groupby("Region").min().reset_index()}")

Avg Sales of each region:
          Region  Total Revenue
0           Asia     280.693125
1         Europe     265.850750
2  North America     453.747561
Max Sales of each region:
          Region  Total Revenue
0           Asia        1895.00
1         Europe        2599.98
2  North America        3899.99
Min Sales of each region:
          Region  Total Revenue
0           Asia          39.60
1         Europe           6.50
2  North America          17.98