# Introduction to Data Analysis with Pandas

Pandas is an open-source Python library built on top of NumPy, first released by Wes McKinney in 2008.
It is a high-level library known for its efficiency in handling structured data. Pandas supports multiple data workflows, including data cleaning, transformation, and analysis, which is why it is essential for data science and artificial intelligence.
It has a large ecosystem of integrations, making it suitable for a wide range of applications, from financial modeling and business analytics to preprocessing features for machine learning models.

Originally, there are 2 core data structures in Pandas:

- Series (1-Dimensional):

The data is structured as a single column of values, capable of holding any data type (integers, strings, floats, etc.).

Every element is explicitly mapped to an axis label, known as the index.

Mathematical operations are vectorized, allowing you to perform calculations across the entire series instantly without writing loops.

- DataFrame (2-Dimensional):

The entire data collection is structured as a tabular spreadsheet with distinct rows and columns.

It is exceptionally faster than native Python collections because the underlying data is stored in contiguous memory blocks.

However, managing memory can become a challenge with massive datasets, as a simple operation can create unintended copies of the entire structure in memory.

In [15]:
# Importing pandas
import pandas as pd

In [16]:
# Creating a series
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
# Performing mathematical operations using series

In [17]:
# Creating a DataFrame
df = pd.DataFrame({
    "name": ["Ali", "Sarah", "George"],
    "marks": [76,89,56]
})
df

     name  marks
0     Ali     76
1   Sarah     89
2  George     56

In [18]:
# Concatenating 2 datasets
df2 = pd.DataFrame({
    "name": ["Daniel", "Mustufa"],
    "marks": [34,98]
})
final_df = pd.concat([df,df2])
final_df

      name  marks
0      Ali     76
1    Sarah     89
2   George     56
0   Daniel     34
1  Mustufa     98

In [19]:
# Merging datasets
df = pd.DataFrame({
    "ID": [1000,1001,1002],
    "name": ["Ali", "Sarah", "Affan"]
})
df2 = pd.DataFrame({
    "name": ["Ali", "Sarah", "Affan"],
    "marks": [78,98,65]
})
final_df = pd.merge(df,df2,on="name")
final_df

     ID   name  marks
0  1000    Ali     78
1  1001  Sarah     98
2  1002  Affan     65

# Basic Data Analysis

In [20]:
# Reading a csv
data = pd.read_csv("Online Sales Data.csv") # creates a DataFrame obj
print(type(data))

<class 'pandas.DataFrame'>

In [3]:
data

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
data.head() # a method which returns first 5 rows by default

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [11]:
data.sample() # returns 1 random row

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
54,10055,2024-02-24,Electronics,Anker PowerCore Portable Charger,4,59.99,239.96,North America,Credit Card

In [12]:
data.tail() # returns last 5 rows from dataset

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [13]:
data.columns # an attr which returns column names

Index(['Transaction ID', 'Date', 'Product Category', 'Product Name',
       'Units Sold', 'Unit Price', 'Total Revenue', 'Region',
       'Payment Method'],
      dtype='str')

In [ ]:
print(f"Total Rows: {data.shape[0]}\nTotal Columns: {data.shape[1]}") # data.shape an attr returning total rows and columns in the form of tuple

Total Rows: 240
Total Columns: 9

In [22]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    str
 2   Product Category  240 non-null    str
 3   Product Name      240 non-null    str
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    str
 8   Payment Method    240 non-null    str
dtypes: float64(2), int64(2), str(5)
memory usage: 17.0 KB

In [23]:
data.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000